apiVersion: v1
kind: Service
metadata:
  name:  rating
spec:
  selector:
    app: rating
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: rating-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: rating-db
